/**
 * THIS SECTION DEFINES ERROR CODES FOR THE THE FULL PROJECTS
 *
 * THE ERROR CODES ARE NAMED BASED ON THE DOMAIN IN WHICH THEY WHERE RAISED
 * EG USER WILL U FOLLOWED BY NUMBERS
 */

export const ERROR_CODES = {
  USER_NOT_FOUND: 'U_NOT_FOUND:001',
  PASSWORD_DO_NOT_MATCH: 'U_PDNM:001',
};
